import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><header className="bg-slate-400 text-4xl">
                 <h1>Header</h1>
               </header>{children}<footer className="bg-slate-400 text-4xl">
        <h1>Footer</h1>
                    </footer></body>
    </html>
  );
}
